name: Build and Deploy website
on:
    push:
      branches:
        - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies (if needed)
        run: |
          if [ -f requirements.txt ]; then
            pip install --no-cache-dir -r requirements.txt
          fi

      - name: Run the script
        run: python build.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          commit-message: "[Automatic deployment] ${{ github.event.head_commit.message }}"