name: Auto-Merge Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for merging


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies (if needed)
        run: |
          if [ -f requirements.txt ]; then
            pip install --no-cache-dir --no-hashes -r requirements.txt
          fi

      - name: Run the script
        run: python build.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push generated files
        run: |
          git switch main
          git add index.html css/ assets/
          git commit -m "Auto-generated index.html and updated CSS"
          git push origin main

      # - name: Merge develop into main
      #   run: |
      #     git checkout main
      #     git merge --ff-only develop || (echo "Merge conflict detected. Manual intervention required." && exit 1)
      #     git push origin main