name: Auto-Merge Develop to Main

on:
  push:
    branches:
      - develop

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history for merging

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git checkout main
          git merge --ff-only develop || (echo "Merge conflict detected. Manual intervention required." && exit 1)
          git push origin main
